core/urls.py
# I created file and wrote code
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

item/urls.py
#I made file and wrote all code here
from django.urls import path

from . import views

app_name = 'item' #import in main url file in penguin

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),#primary key
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

penguin/urls.py
from django.contrib import admin
from django.urls import path, include
# my import below
# from core.views import index, contact (not needed anymore)
# below cheating hack to display photos on front page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #add line below
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    #add line above
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models

# Create your models here.
# I added all the code below
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)
# once I write code above
# I write in terminal: 'python manage.py makemigrations'
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories' # to change item name in django administration
    def __str__(self):# to show/display (category)names
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    #text field longer than char field
    understanding = models.FloatField()
    image = models.ImageField(upload_to='image', blank=True, null=True)
    #python will create this folder for us if it doesn't exist
    watched = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    #if user is deleted all items will also be deleted
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'understanding', 'image',)

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'understanding': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'understanding', 'image', 'watched')

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'understanding': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
# I added get_object_or_404

# Create your views here.
# I wrote code below

from django.contrib.auth.decorators import login_required
from .models import Item
from .forms import NewItemForm, EditItemForm


def items(request):
    items = Item.objects.filter(watched=False)
    watched_items = Item.objects.filter(watched=True)

    return render(request, 'item/items.html', {
        'items': items,
        'watched_items': watched_items,
    })

def detail(request, pk):#primary key
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, watched=False).exclude(pk=pk)[0:3]
    # related_watched = Item.objects.filter(category=item.category, watched=True).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False) #we have to create object first then save to data base
            item.created_by = request.user
            item.user()
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New item',
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item',
    })

@login_required
def delete(request, pk):#pk which is id for item we want to delete
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6"><!--grid so image on left and description on right-->
    <div class="col-span-3">
        {% if item.image %}
        <img src="{{ item.image.url }}" class="rounded-xl">
        {% endif %}
    </div>

    <div class="col-span-2 p-6 bg-green-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{item.name}}</h1>
        <p class="text-gray-500"><strong>Understanding: </strong>{{ item.understanding }}</p>
        <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by.username }}</p>
        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ item.description }}
            </p>
        {% endif %}
        <p class="text-gray-500"><strong>Rating: </strong>### Reviews</p>

        {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your item!</p>

                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-300 text-white rounded-xl">Edit</a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
            </div>
        {% else %}
            <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-pink-400 text-white rounded-xl hover:bg-pink-700">Contact Seller</a>
        {% endif %}
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related items</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl"><!--last bit so there are rounded corners-->
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Understanding: {{ item.understanding }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_erros }}
            </div>
        {% endif %}

        <button class="mt-6 py-4 px-8 text-lg bg-pink-400 hover:bg-pink-700 rounded-xl text-white">Submit</button><!--mt-6 adds space between button and the top-->
</form>
{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Items{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4">
        <div class="cols-span-2">
            <form method="get" action="{% url 'item:items' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find by name or catagory">

                <button class="mt-2 py-4 px-8 text-lg bg-pink-400 text-white rounded-xl">Search</button>
                </input>
            </form>
        </div>
        <div class="col-span-3">
            <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
                <div class="grid grid-cols-1 gap-2">
                    {% for item in items %}
                        <div>
                            <a href="{% url 'item:detail' item.id %}">
                                <div>
                                    {% if item.image %}
                                    <img src="{{ item.image.url }}" class="rounded-t-xl"><!--last bit so there are rounded corners-->
                                    {% endif %}
                                </div>
                                <div class="p-3 bg-white rounded-b-xl">
                                    <h2 class="text-2xl">{{ item.name }}</h2>
                                    <p class="text-gray-500">Understanding: {{ item.understanding }}</p>
                                
                                </div>
                            </a>
                    {% endfor %}
                    {% for item in watched_items %}
                        <div>
                            <a href="{% url 'item:detail' item.id %}">
                                <div>
                                    {% if item.image %}
                                    <img src="{{ item.image.url }}" class="rounded-t-xl"><!--last bit so there are rounded corners-->
                                    {% endif %}
                                </div>
                                <div class="p-3 bg-white rounded-b-xl">
                                    <h2 class="text-2xl">{{ item.name }}</h2>
                                    <p class="text-gray-500">Understanding: {{ item.understanding }}</p>
                                    <p class="text-pink-400">Watched</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}